before_install:
- wget http://www.deflaker.org/maven/apache-maven-3.3.9.zip
- unzip -qq apache-maven-3.3.9.zip
- export M2_HOME=$PWD/apache-maven-3.3.9
- export PATH=$M2_HOME/bin:$PATH
- rm ~/.m2/settings.xml
- nvm install 6.5.0
- node --version
- npm install -g npm@3.10.8
- npm --version
- npm install -g bower
- npm install -g grunt && npm install -g grunt-cli
- grunt --version
- ruby -v
- gem install sass -v 3.3.14
- sass -v
- gem install compass -v 1.0.1
- compass version
env:
- MAVEN_OPTS=-Xmx1024M
install: echo 'Skipping install stage, dependencies will be downloaded during build and test stages.'
jdk:
- oraclejdk8
language: java
notifications:
  email: false
  slack:
    rooms: flakycov:U2MeVOPjdi4up1U793ubeIUZ
    template:
    - Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration}
    - 'dashbot: %{repository_name} %{build_id}'
sudo: false

# Two stage Build and Test
# 1. Install & Unit Test APIs
# 2. Assemble DSpace
script:
  # 1. [Install & Unit Test] Check source code licenses and run source code Unit Tests
  #        license:check => Validate all source code license headers
  #        -Dmaven.test.skip=false => Enable DSpace Unit Tests
  #        -DskipITs=false         => Enable DSpace Integration Tests
  #        -P !assembly            => Skip normal assembly (as it can be memory intensive)
  #        -B => Maven batch/non-interactive mode (recommended for CI)
  #        -V => Display Maven version info before build
  #        -Dsurefire.rerunFailingTestsCount=2 => try again for flakey tests, and keep track of/report on number of retries
  - "mvn clean install license:check -Dmaven.test.skip=false -DskipITs=false -P !assembly -B -V -Dsurefire.rerunFailingTestsCount=2"
  # 2. [Assemble DSpace] Ensure overlay & assembly process works (from [src]/dspace/)
  #        -P !assembly => SKIP the actual building of [src]/dspace/dspace-installer (as it can be memory intensive)
  - "cd dspace && mvn package -P !assembly -B -V -Dsurefire.rerunFailingTestsCount=2"
